#!/usr/bin/env bash
set -Eeuo pipefail

# Non-interactive bootstrap for a fresh Ubuntu VPS.
# Edit the variables below or override them via environment variables.
#
# Example:
#   NODE_SECRET_KEY='replace-me' bash start.sh
#   MASTER_NODE_IP='95.85.230.183' EXTRA_TCP_PORTS='' NODE_SECRET_KEY='replace-me' bash start.sh

SSH_PORT="${SSH_PORT:-22}"
MASTER_NODE_IP="${MASTER_NODE_IP:-95.85.230.183}"
EXTRA_TCP_PORTS="${EXTRA_TCP_PORTS:-7443 8443 9443}"

NODE_PORT="${NODE_PORT:-2222}"
NODE_SECRET_KEY="${NODE_SECRET_KEY:-KEY}"

FAIL2BAN_BANTIME="${FAIL2BAN_BANTIME:-1h}"
FAIL2BAN_MAXRETRY="${FAIL2BAN_MAXRETRY:-3}"
FAIL2BAN_FINDTIME="${FAIL2BAN_FINDTIME:-600}"
FAIL2BAN_IGNORE_IPS="${FAIL2BAN_IGNORE_IPS:-127.0.0.1/8 ::1 ${MASTER_NODE_IP}}"

INSTALL_DOCKER="${INSTALL_DOCKER:-1}"
INSTALL_RESHALA="${INSTALL_RESHALA:-1}"
INSTALL_TRAFFICGUARD="${INSTALL_TRAFFICGUARD:-1}"
INSTALL_REMNANODE="${INSTALL_REMNANODE:-1}"
INSTALL_MULTITEST="${INSTALL_MULTITEST:-1}"

ENABLE_KERNEL_HARDENING="${ENABLE_KERNEL_HARDENING:-1}"
ENABLE_BBR="${ENABLE_BBR:-1}"
ENABLE_RKHUNTER="${ENABLE_RKHUNTER:-0}"
DISABLE_IPV6="${DISABLE_IPV6:-1}"

export DEBIAN_FRONTEND=noninteractive
export NEEDRESTART_MODE=a

CURRENT_STEP=0
TOTAL_STEPS=12

log() {
  printf '[%02d/%02d] %s\n' "${CURRENT_STEP}" "${TOTAL_STEPS}" "$1"
}

next_step() {
  CURRENT_STEP=$((CURRENT_STEP + 1))
  log "$1"
}

require_root() {
  if [[ "${EUID}" -ne 0 ]]; then
    echo "Run as root."
    exit 1
  fi
}

require_secret_if_needed() {
  if [[ "${INSTALL_REMNANODE}" == "1" && "${NODE_SECRET_KEY}" == "KEY" ]]; then
    echo "Set NODE_SECRET_KEY before running the script."
    exit 1
  fi
}

trim() {
  local value="$1"
  value="${value#"${value%%[![:space:]]*}"}"
  value="${value%"${value##*[![:space:]]}"}"
  printf '%s' "${value}"
}

validate_port() {
  local port="$1"
  [[ "${port}" =~ ^[0-9]+$ ]] && (( port >= 1 && port <= 65535 ))
}

ensure_base_packages() {
  apt-get update
  apt-get -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" -y full-upgrade
  apt-get install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    fail2ban \
    gpg \
    iproute2 \
    ipset \
    net-tools \
    rsyslog \
    software-properties-common \
    ufw \
    wget \
    whois
  apt-get autoremove -y
  apt-get autoclean -y
}

install_docker() {
  if command -v docker >/dev/null 2>&1 && docker compose version >/dev/null 2>&1; then
    systemctl enable --now docker
    return
  fi

  install -m 0755 -d /etc/apt/keyrings
  if [[ ! -f /etc/apt/keyrings/docker.gpg ]]; then
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg
  fi

  . /etc/os-release
  cat > /etc/apt/sources.list.d/docker.list <<EOF
deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu ${VERSION_CODENAME} stable
EOF

  apt-get update
  apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  systemctl enable --now docker
}

apply_kernel_hardening() {
  cat > /etc/sysctl.d/99-reshala-hardening.conf <<'EOF'
# Generated by bootstrap-remnanode-stack.sh

# SYN flood protection
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_synack_retries = 2
net.ipv4.tcp_syn_retries = 2
net.ipv4.tcp_max_syn_backlog = 4096
net.core.somaxconn = 4096
net.core.netdev_max_backlog = 4096

# Anti-spoofing and redirect hardening
net.ipv4.conf.all.accept_source_route = 0
net.ipv4.conf.default.accept_source_route = 0
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.default.rp_filter = 1
net.ipv4.conf.all.accept_redirects = 0
net.ipv4.conf.default.accept_redirects = 0
net.ipv4.conf.all.secure_redirects = 0
net.ipv4.conf.default.secure_redirects = 0
net.ipv6.conf.all.accept_redirects = 0
net.ipv6.conf.default.accept_redirects = 0
net.ipv4.icmp_echo_ignore_broadcasts = 1
net.ipv4.icmp_ignore_bogus_error_responses = 1

# TCP tuning
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_fin_timeout = 15
net.ipv4.tcp_keepalive_time = 600
net.ipv4.tcp_keepalive_probes = 5
net.ipv4.tcp_keepalive_intvl = 15

# Kernel security
kernel.randomize_va_space = 2
kernel.dmesg_restrict = 1
kernel.yama.ptrace_scope = 1
fs.protected_symlinks = 1
fs.protected_hardlinks = 1
EOF

  sysctl -p /etc/sysctl.d/99-reshala-hardening.conf >/dev/null
}

apply_bbr() {
  local preferred_cc="bbr"
  local preferred_qdisc="fq"

  modprobe sch_cake >/dev/null 2>&1 || true
  if sysctl net.ipv4.tcp_available_congestion_control 2>/dev/null | grep -q 'bbr2'; then
    preferred_cc="bbr2"
  fi
  if lsmod | grep -q '^sch_cake'; then
    preferred_qdisc="cake"
  fi

  cat > /etc/sysctl.d/99-bootstrap-bbr.conf <<EOF
# Generated by bootstrap-remnanode-stack.sh
net.core.default_qdisc = ${preferred_qdisc}
net.ipv4.tcp_congestion_control = ${preferred_cc}
net.ipv4.tcp_fastopen = 3
net.core.rmem_max = 16777216
net.core.wmem_max = 16777216
net.ipv4.tcp_rmem = 4096 87380 16777216
net.ipv4.tcp_wmem = 4096 65536 16777216
EOF

  sysctl -p /etc/sysctl.d/99-bootstrap-bbr.conf >/dev/null
}

configure_ipv6() {
  if [[ "${DISABLE_IPV6}" != "1" ]]; then
    rm -f /etc/sysctl.d/98-disable-ipv6.conf
    return
  fi

  cat > /etc/sysctl.d/98-disable-ipv6.conf <<'EOF'
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
EOF

  sysctl -p /etc/sysctl.d/98-disable-ipv6.conf >/dev/null
}

configure_ufw() {
  if [[ -f /etc/default/ufw ]]; then
    if [[ "${DISABLE_IPV6}" == "1" ]]; then
      sed -i 's/^IPV6=.*/IPV6=no/' /etc/default/ufw || true
    else
      sed -i 's/^IPV6=.*/IPV6=yes/' /etc/default/ufw || true
    fi
  fi

  ufw --force reset
  ufw default deny incoming
  ufw default allow outgoing

  ufw allow "${SSH_PORT}/tcp" comment 'SSH'
  ufw allow 443/tcp comment 'VPN/HTTPS'

  if [[ -n "$(trim "${MASTER_NODE_IP}")" ]]; then
    ufw allow from "${MASTER_NODE_IP}" comment 'Master Node Full Access'
  fi

  local port
  for port in ${EXTRA_TCP_PORTS}; do
    if validate_port "${port}"; then
      ufw allow "${port}/tcp" comment 'Custom VPN'
    fi
  done

  ufw --force enable
  ufw reload
}

detect_fail2ban_backend() {
  if command -v journalctl >/dev/null 2>&1; then
    printf 'systemd'
  else
    printf 'auto'
  fi
}

configure_fail2ban() {
  install -d -m 0755 /etc/fail2ban/jail.d

  cat > /etc/fail2ban/jail.d/sshd.local <<EOF
[DEFAULT]
bantime = ${FAIL2BAN_BANTIME}
findtime = ${FAIL2BAN_FINDTIME}
maxretry = ${FAIL2BAN_MAXRETRY}
backend = $(detect_fail2ban_backend)
banaction = ufw
banaction_allports = ufw
ignoreip = ${FAIL2BAN_IGNORE_IPS}

[sshd]
enabled = true
port = ${SSH_PORT}
logpath = %(sshd_log)s
EOF

  fail2ban-client -t >/dev/null
  systemctl enable fail2ban
  systemctl restart fail2ban
}

install_rkhunter() {
  apt-get install -y rkhunter
  rkhunter --update || true
  rkhunter --propupd || true

  cat > /etc/cron.weekly/bootstrap-rkhunter <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
rkhunter --update --quiet || true
rkhunter --check --cronjob --report-warnings-only > /var/log/bootstrap-rkhunter.log 2>&1 || true
EOF
  chmod +x /etc/cron.weekly/bootstrap-rkhunter
}

install_reshala() {
  wget -4 -O /root/install-reshala.sh https://raw.githubusercontent.com/DonMatteoVPN/Reshala-Remnawave-Bedolaga/main/install.sh
  bash /root/install-reshala.sh
}

install_trafficguard() {
  local temp_script
  temp_script="$(mktemp /tmp/install-trafficguard.XXXXXX.sh)"
  curl -fsSL https://raw.githubusercontent.com/DonMatteoVPN/TrafficGuard-auto/refs/heads/main/install-trafficguard.sh -o "${temp_script}"
  sed -i 's#^/opt/trafficguard-manager\.sh monitor$#echo "TrafficGuard installed without autostart monitor."#' "${temp_script}"
  bash "${temp_script}"
  rm -f "${temp_script}"
}

install_remnanode() {
  curl -Ls https://github.com/DigneZzZ/remnawave-scripts/raw/main/remnanode.sh \
    | bash -s -- @ install \
        --force \
        --secret-key="${NODE_SECRET_KEY}" \
        --port="${NODE_PORT}" \
        --xray
}

install_multitest() {
  curl -fsSL https://raw.githubusercontent.com/saveksme/multitest/master/multitest.sh \
    -o /usr/local/bin/multitest
  chmod +x /usr/local/bin/multitest
  command -v multitest >/dev/null 2>&1
}

print_summary() {
  CURRENT_STEP="${TOTAL_STEPS}"
  echo
  echo "Bootstrap completed."
  echo
  echo "Configuration:"
  echo "  SSH_PORT=${SSH_PORT}"
  echo "  MASTER_NODE_IP=${MASTER_NODE_IP:-<empty>}"
  echo "  EXTRA_TCP_PORTS=${EXTRA_TCP_PORTS:-<none>}"
  echo "  NODE_PORT=${NODE_PORT}"
  echo "  FAIL2BAN_BANTIME=${FAIL2BAN_BANTIME}"
  echo "  FAIL2BAN_MAXRETRY=${FAIL2BAN_MAXRETRY}"
  echo "  FAIL2BAN_FINDTIME=${FAIL2BAN_FINDTIME}"
  echo
  echo "Installed status:"
  if command -v docker >/dev/null 2>&1; then
    echo "  Docker: yes"
  else
    echo "  Docker: no"
  fi
  if systemctl is-active --quiet ufw; then
    echo "  UFW: active"
  else
    echo "  UFW: inactive"
  fi
  if systemctl is-active --quiet fail2ban; then
    echo "  Fail2Ban: active"
  else
    echo "  Fail2Ban: inactive"
  fi
  if command -v rknpidor >/dev/null 2>&1; then
    echo "  TrafficGuard: installed"
  else
    echo "  TrafficGuard: not installed"
  fi
  if command -v remnanode >/dev/null 2>&1; then
    echo "  RemnaNode: installed"
  else
    echo "  RemnaNode: not installed"
  fi
  if command -v multitest >/dev/null 2>&1; then
    echo "  multitest: installed"
  else
    echo "  multitest: not installed"
  fi
  if command -v reshala >/dev/null 2>&1; then
    echo "  Reshala: installed"
  else
    echo "  Reshala: not installed"
  fi
  if command -v rkhunter >/dev/null 2>&1; then
    echo "  rkhunter: installed"
  else
    echo "  rkhunter: not installed"
  fi
  echo
  echo "Checks:"
  fail2ban-client status sshd || true
  echo
  ufw status verbose || true
  echo
  sysctl net.ipv4.tcp_congestion_control net.core.default_qdisc 2>/dev/null || true
  if [[ "${DISABLE_IPV6}" == "1" ]]; then
    sysctl net.ipv6.conf.all.disable_ipv6 2>/dev/null || true
  fi
  echo
  docker ps --format 'table {{.Names}}\t{{.Status}}' 2>/dev/null || true
  echo
  echo "Useful commands:"
  echo "  remnanode status"
  echo "  docker ps"
  echo "  ufw status verbose"
  echo "  fail2ban-client status sshd"
  echo "  systemctl status fail2ban --no-pager"
  echo "  ss -tulpn"
  echo "  rknpidor"
  echo "  multitest"
  if command -v reshala >/dev/null 2>&1; then
    echo "  reshala"
  fi
}

main() {
  require_root
  require_secret_if_needed

  next_step "Updating system and installing base packages..."
  ensure_base_packages

  next_step "Installing Docker..."
  if [[ "${INSTALL_DOCKER}" == "1" ]]; then
    install_docker
  fi

  next_step "Applying optional kernel hardening..."
  if [[ "${ENABLE_KERNEL_HARDENING}" == "1" ]]; then
    apply_kernel_hardening
  fi

  next_step "Applying optional BBR/CAKE tuning..."
  if [[ "${ENABLE_BBR}" == "1" ]]; then
    apply_bbr
  fi

  next_step "Configuring IPv6 policy..."
  configure_ipv6

  next_step "Configuring UFW..."
  configure_ufw

  next_step "Configuring Fail2Ban..."
  configure_fail2ban

  next_step "Installing optional rkhunter..."
  if [[ "${ENABLE_RKHUNTER}" == "1" ]]; then
    install_rkhunter
  fi

  next_step "Installing TrafficGuard..."
  if [[ "${INSTALL_TRAFFICGUARD}" == "1" ]]; then
    install_trafficguard
  fi

  next_step "Installing optional multitest..."
  if [[ "${INSTALL_MULTITEST}" == "1" ]]; then
    install_multitest
  fi

  next_step "Installing RemnaNode..."
  if [[ "${INSTALL_REMNANODE}" == "1" ]]; then
    install_remnanode
  fi

  next_step "Installing optional utilities..."
  if [[ "${INSTALL_RESHALA}" == "1" ]]; then
    install_reshala
  fi

  print_summary
}

main "$@"
